stages:
  - docker-build
  - deploy

docker-build:
  stage: docker-build
  image: registry.cn-shanghai.aliyuncs.com/choerodon/devops-ci:1.0.1
  script:
    - docker_build
  only:
    - gh-pages

deploy:
  stage: deploy
  image: registry.cn-shanghai.aliyuncs.com/choerodon/kubectl:v1.8.5
  script:
    - deploy
  only:
    - gh-pages

.auto_devops: &auto_devops |
  export CI_APPLICATION_TAG=$CI_COMMIT_REF_NAME-${CI_COMMIT_SHA:0:8}
  if [ ! $CI_COMMIT_TAG ]; then
    export CI_COMMIT_TAG=$CI_APPLICATION_TAG
  fi

  function docker_build() {
    # docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $REGISTRY_ADDRESS
    docker login -u $REGISTRY_USER -p $REGISTRY_PWD $REGISTRY_ADDRESS
    docker build --pull -t $REGISTRY_ADDRESS/hap/chochoerodon-ui:$CI_COMMIT_TAG .
    docker push $REGISTRY_ADDRESS/hap/chochoerodon-ui:$CI_COMMIT_TAG
  }

  function deploy() {
    sed -i 's/server:.*$/server:\ '${KUBERNETES_SERVER}'/g' auto_devops/config
    sed -i 's/token:.*$/token:\ '${KUBERNETES_TOKEN}'/g' auto_devops/config
    sed -i 's/\$CI_COMMIT_TAG/'${CI_COMMIT_TAG}'/g' auto_devops/deploy-template.yml
    sed -i 's/-\ host:.*$/-\ host:\ '${INGRESS_HOST}'/g' auto_devops/deploy-template.yml
    cat auto_devops/deploy-template.yml
    cat auto_devops/config
    cp auto_devops/config ~/.kube/config
    kubectl apply -f auto_devops/deploy-template.yml -n ${K8S_NAMESPACE}
  }

before_script:
  - *auto_devops
