apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: chochoerodon-ui
  name: chochoerodon-ui
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: chochoerodon-ui
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: chochoerodon-ui
    spec:
      containers:
      - image: registry.cn-shanghai.aliyuncs.com/choerodon/chochoerodon-ui:$CI_COMMIT_TAG
        imagePullPolicy: Always
        name: chochoerodon-ui
        ports:
        - containerPort: 80
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: chochoerodon-ui
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: chochoerodon-ui
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: chochoerodon-ui
spec:
  rules:
  - host:
    http:
      paths:
      - backend:
          serviceName: chochoerodon-ui
          servicePort: 80
